### ISSUE TITLE
Add 'add server' button to the `Navigation` component's server list items

### ISSUE THREAD

**Issue by yurixander** [yurixander/mirage#15]
The 'add server' button should always be at the end of the server list. It should have a tooltip with something like "Create new server" and an `onClick` event as a prop.

#### Reference

![image](https://github.com/yurixander/mirage/assets/101931215/92adef5d-a001-48ac-aaad-211834d1c5fe)

**Comment by Tokyotox** [comment]
“The button was created alongside another component, see #14”
