### ISSUE TITLE
Research and provide suggestions for icons library

### ISSUE THREAD

**Issue by yurixander** [yurixander/mirage#4]
We need an icons library to use for our React project. The ideal library will:
* Integrate nicely with React.
* Have TypeScript type definitions.

The ones that we could start considering would be:
* [Lucide](https://lucide.dev/)
* [FontAwesome](https://fontawesome.com/)

Provide some feedback here or additional suggestions if you find more libraries that might be worth looking into.

**Comment by Tokyotox** [comment]
We are going to use Lucide

All designs are consistent
There is support for TypeScript and React
It has already been installed in the project.
